# Generated by Django 4.0.5 on 2022-10-26 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_post_fiyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.IntegerField(verbose_name='Ürün Fiyatı')),
                ('adet', models.IntegerField(verbose_name='Ürün Adeti')),
                ('image', models.FileField(upload_to='post', verbose_name='Ürün Foroğrafı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.post', verbose_name='Ürün Adı')),
            ],
        ),
    ]
